# Generated by Django 4.1.7 on 2023-03-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='demo.png', null=True, upload_to='course_imgs/'),
        ),
    ]
