# Generated by Django 4.1.7 on 2023-03-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default='demo.png', null=True, upload_to='course_imgs/'),
        ),
    ]
