# Generated by Django 4.1.7 on 2023-03-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_avatar_user_bio_user_name_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='user.png', null=True, upload_to='avatar/'),
        ),
    ]
